#@package _global_
defaults:
  - /analysis/logs/dna_guided_nca_metrics@analysis
  - /analysis/plots/mpe_repertoire@analysis
  - /analysis/plots/level_gen@analysis
  # - /analysis/plots/dna_attn_seq@analysis
  - /analysis/plots/dna_attn_max@analysis
  - /analysis/plots/input_output_dissimilarity@analysis
  # - /analysis/plots/dna_distribution_comparison@analysis
  # - /analysis/plots/dna_measure_projection@analysis
  # - /analysis/plots/sparse_dna_to_metric_regression@analysis
  # - /analysis/plots/dna_to_metric_cross_decomposition@analysis
  # - /analysis/plots/dna_path_length_intervention@analysis

tags: ["dnaqd", "simple_level_gen", "nca_dna", "evo"]

overrides:
  model:
    nca:
      output_dev_steps: True
