_target_: src.model.dev.NCA

dev_steps: [46, 96]
state_size: 16
grid_size: ???  # set in each experiment
update_prob: 0.5

context_encoder:
  _target_: src.nn.dna.DNAContextEncoder
  alphabet_size: ???
  sequence_length: ???
  embedding_size: 16
  input_is_distribution: True
  key: ${prng_key:}

control_fn:
  _target_: src.nn.dna.DNAControl
  n_heads: 1
  state_size: ???
  dna_emb_size: 16
  key: ${prng_key:}

alive_fn:
  _target_: src.nn.ca.MaxPoolAlive
  alive_threshold: 0.1
  alive_bit: 3

message_fn:
  _target_: src.nn.ca.IdentityAndSobelFilter

update_fn:
  _target_: equinox.nn.Sequential
  layers:
    - _target_: equinox.nn.Conv2d
      in_channels: ${prod:${model.state_size},3}
      out_channels: 128
      kernel_size: 1
      key: ${prng_key:}
    - _target_: equinox.nn.Lambda
      fn: ${get_fn:jax.nn.relu}
    - _target_: equinox.nn.Conv2d
      in_channels: 128
      out_channels: ${model.state_size}
      kernel_size: 1
      key: ${prng_key:}

output_decoder: ???
