defaults:
  - /model@dna_sampler: dna_iid_sampler

_target_: src.task.dnaqd.PersistentQDSearchDNA

popsize: 100
n_iters: 10
n_centroids: 1000
n_centroid_samples: null

score_aggregator: null  # default aggregates qd_score and coverage

qd_algorithm: ???
problem: ???
